# Generated by Django 5.0.2 on 2024-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(db_index=True)),
                ('short_url', models.TextField(db_index=True)),
            ],
        ),
    ]
